imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: facebook.yml }
    - { resource: services.yml }
    - { resource: knp.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    translator: { fallback: en }

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
#    form:
#        resources:
#            - 'CyclogramFrontendBundle:Form:fields.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            limesurvey:
                driver:   %database_driver%
                host:     %lime_database_host%
                port:     %lime_database_port%
                dbname:   %lime_database_name%
                user:     %lime_database_user%
                password: %lime_database_password%
                charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default # specify the EM used by default (when using console commands f.e)
        entity_managers:
            default:
                connection: default
                mappings:
                    CyclogramProofPilotBundle : ~   
            limesurvey:
                connection: limesurvey
                mappings:
                    CyclogramSexProBundle: ~     

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    encryption: %mailer_encryption%
    spool:     { type: memory }
    
#Lunetics locale
lunetics_locale:
    allowed_locales: %locales%
    guessing_order:
        - query
        - router
        - browser
    strict_mode: true
    
#JMS Translation
jms_translation:
    configs:
        app:
            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: [routes, validators]
            excluded_names: [*TestCase.php, *Test.php]
            excluded_dirs: [cache, data, logs, Acme]
            #extractors: [alias_of_the_extractor]
    locales: %locales%

jms_aop:
    cache_dir: %kernel.cache_dir%/jms_aop



