imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: oauth2.yml }    
    - { resource: services.yml }
    - { resource: knp.yml }
    
parameters:
    twig.extension.routing.class: Cyclogram\FrontendBundle\Twig\RoutingExtension
    hwi_oauth.authentication.listener.oauth.class: Cyclogram\FrontendBundle\Listener\OAuthListener

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: "%assets_version%"
        assets_base_urls:
            http: [%url_assets%]
            ssl:  [%url_assets_ssl%]
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    translator: { fallback: en }

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        facebook_secret: %facebook.secret%
        facebook_appid: '%facebook.appid%'
        google_clientid: %google.client_id%
        google_clientsecret: %google.client_secret%
        google_analytics_account: %google_analytics_account%
        branding: %branding%
        random_themes: %random_themes%
        study_image_url: %study_image_url%
        site_url: %site_url%
        url_assets: %url_assets%
    form:
        resources:
            - 'CyclogramFrontendBundle:Form:fields.html.twig'
#            - 'CyclogramFrontendBundle:Form:frontend_widgets.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    #bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar
        handlebars:
            apply_to: %handlebars.extension%
            bin: %handlebars.bin%
            node: %handlebars.node%

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                port:     %database_port%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            limesurvey:
                driver:   %database_driver%
                host:     %lime_database_host%
                port:     %lime_database_port%
                dbname:   %lime_database_name%
                user:     %lime_database_user%
                password: %lime_database_password%
                charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        default_entity_manager: default # specify the EM used by default (when using console commands f.e)
        entity_managers:
            default:
                dql:
                    datetime_functions:
                        datediff: Cyclogram\FrontendBundle\DQL\DateDiffFunction
                    string_functions:
                        cast: Cyclogram\FrontendBundle\DQL\CastFunction
                connection: default
                mappings:
                    CyclogramProofPilotBundle : ~   
            limesurvey:
                connection: limesurvey
                mappings:
                    CyclogramProofPilotBundle: 
                        mapping:              true
                        type:                 annotation
                        dir:                  %kernel.root_dir%/../src/Cyclogram/Bundle/ProofPilotBundle/Entity/LimeSurvey
                        alias:                CyclogramProofPilotBundleLime
                        prefix:               Cyclogram\Bundle\ProofPilotBundle\Entity\LimeSurvey
                        is_bundle:            false


# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    encryption: %mailer_encryption%
#    spool:     { type: file }
    
#Lunetics locale
lunetics_locale:
    allowed_locales: %locales%
    guessing_order:
        - query
        - router
        - browser
    strict_mode: true
    
#JMS Translation
jms_translation:
    configs:
        app:
            dirs: [%kernel.root_dir%, %kernel.root_dir%/../src]
            output_dir: %kernel.root_dir%/Resources/translations
            ignored_domains: [routes, validators]
            excluded_names: [*TestCase.php, *Test.php]
            excluded_dirs: [cache, data, logs, Acme, LimeSurvey]
            #extractors: [alias_of_the_extractor]
    locales: %locales%

#JMS Aspect-oriented-programming
jms_aop:
    cache_dir: %kernel.cache_dir%/jms_aop
    




