fos_facebook:
#    file:   %kernel.root_dir%/../vendor/facebook/php-sdk/src/base_facebook.php
    alias:  facebook
    app_id: %facebook.appid%
    secret: %facebook.secret%
    cookie: true
    permissions: [email]


services:
    my.facebook.user:
        class: Cyclogram\SexProBundle\Security\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@doctrine.orm.entity_manager"
            validator: "@validator"
            container: "@service_container"
            
    fos_facebook.helper:
        class: Cyclogram\SexProBundle\Templating\Helper\FacebookHelper
        arguments:
            - @templating
            - @fos_facebook.api
            - %fos_facebook.logging%
            - %fos_facebook.culture%
            - %fos_facebook.permissions%
        tags:
            - { name: templating.helper, alias: facebook } 
