cyclogram_frontend:
    resource: "@CyclogramFrontendBundle/Controller/"
    type:     annotation
    prefix:   /

_root:
    pattern: /
    defaults:
        _controller: lunetics_locale.switcher_controller:switchAction
        route: _page
        statusCode: 301
        useReferrer: false
        routeParameters:
            studyUrl: 'sexpro'

cyclogram_proof_pilot:
    resource: "@CyclogramProofPilotBundle/Controller/"
    type:     annotation
    prefix:   /

cyclogram_sex_pro:
    resource: "@CyclogramSexProBundle/Controller/"
    type:     annotation
    prefix: /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
