hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
google_login:
    pattern: /check_google
    
facebook_login:
    pattern: /check_facebook
    
frontend_oauth_service_redirect:
    pattern: /redirect/{service}
    defaults:
        _controller: CyclogramFrontendBundle:Authentification:redirectToService
        
#_bazinga_exposetranslation:
#    resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"


_root:
    path: /
    defaults:
        _controller: lunetics_locale.switcher_controller:switchAction
        route: _index
        statusCode: 301
        useReferrer: false

cyclogram_frontend:
    resource: "@CyclogramFrontendBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: en|es|pt|fr|es_MX|pt_BR|chn

cyclogram_study:
    resource: "@CyclogramStudyBundle/Controller/"
    type:     annotation
    prefix: /{_locale}
    requirements:
        _locale: en|es|pt|fr|es_MX|pt_BR|chn

_study_switch:
    path: /{study}/
    requirements:
        study: "[0-9a-zA-Z ]+"
    defaults:
        _controller: lunetics_locale.switcher_controller:switchStudyAction
        route: _page
        statusCode: 301
        useReferrer: false

#CyclogramKnowatHomeBundle:
#    resource: "@CyclogramKnowatHomeBundle/Resources/config/routing.yml"
#    prefix:   /{_locale}/{studyCode}
#    requirements:
#        _locale: en|es|pt|fr|es_MX|pt_BR
#        studyCode: knowathome|eStamp4








    
