hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
google_login:
    pattern: /check_google
    
facebook_login:
    pattern: /check_facebook
    
frontend_oauth_service_redirect:
    pattern: /redirect/{service}
    defaults:
        _controller: CyclogramFrontendBundle:Login:redirectToService


_root:
    path: /{study}/
    requirements:
        study: "[0-9a-zA-Z ]*"
    defaults:
        _controller: lunetics_locale.switcher_controller:switchAction
        route: _page
        statusCode: 301
        useReferrer: false

CyclogramKnowatHomeBundle:
    resource: "@CyclogramKnowatHomeBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/knowathome

cyclogram_frontend:
    resource: "@CyclogramFrontendBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale: en|es|pt|fr|es_MX|pt_BR

cyclogram_study:
    resource: "@CyclogramStudyBundle/Controller/"
    type:     annotation
    prefix: /{_locale}/{studyUrl}
    requirements:
        _locale: en|es|pt|fr|es_MX|pt_BR


    
