security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Cyclogram\SexProBundle\Entity\User: plaintext

    always_authenticate_before_granting: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: CyclogramSexProBundle:User, property: userEmail }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/sexpro/login$
            security: false
            anonymous:  ~

        secured_area:
            pattern: ^/
            anonymous:  ~
            form_login:
                check_path: /sexpro/login_check
                login_path: /sexpro/login
                default_target_path: /sexpro/doLogin
                always_use_default_target_path: true
            logout:
                path:   /sexpro/logout
                target: /

    access_control:
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/r/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/no-authorization, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sexpro/doLogin, roles: ROLE_USER }
        - { path: ^sexpro/loginSMS, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_USER }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }