security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Cyclogram\StudyBundle\Entity\User: plaintext
        Cyclogram\Bundle\ProofPilotBundle\Entity\Participant: plaintext

    always_authenticate_before_granting: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_FACEBOOK_USER: ROLE_USER

    providers:
        chain_provider: 
            chain:
                providers: [main, fos_facebook]
        main:
            entity: { class: CyclogramProofPilotBundle:Participant }
        fos_facebook:
            id: my.facebook.user

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            anonymous:  ~
            fos_facebook:
                provider: fos_facebook
                check_path: _fb_security_check
                login_path: _login
                app_url: "http://apps.facebook.com/Proofpilot_sexpro/"
                server_url: "http://localhost/facebookApp/"
            form_login:
                provider: main
                check_path: login_check
                login_path: _login
                default_target_path: _do_login
                always_use_default_target_path: true
            logout:
                path:   _logout
                target: _login

    access_control:
        - { path: "^/[a-z]{2}-[a-z]{2}/main$", roles: ROLE_USER }
        - { path: "^/[a-z]{2}-[a-z]{2}/secured/.*", role: [IS_AUTHENTICATED_FULLY] }
        - { path: "^/[a-z]{2}-[a-z]{2}/register$", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/api$", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/r/", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/no-authorization", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/[a-z]{2}-[a-z]{2}/doLogin$", roles: ROLE_USER }
        - { path: "^/[a-z]{2}-[a-z]{2}/loginSMS$", roles: ROLE_USER }
        - { path: "^/$", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/[a-z]{2}-[a-z]{2}/", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/[a-z]{2}-[a-z]{2}/reg_step2$", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/[a-z]{2}-[a-z]{2}/reg_step3$", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "^/[a-z]{2}-[a-z]{2}/reg_step4$", roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }