services:
    cyclogram.common:
        class: Cyclogram\CyclogramCommon
        arguments: ['@service_container']
        
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension