services:
    cyclogram.common:
        class: Cyclogram\CyclogramCommon
        arguments: ['@service_container']
        
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension
            
    twig.globals_extension:
        class: Cyclogram\FrontendBundle\Twig\GlobalExtension
        tags:
            - name: twig.extension
        arguments:
            - @service_container

    lunetics_locale.switcher_controller:
        class: Cyclogram\FrontendBundle\Controller\LocaleController
        arguments:
            - @router
            - @lunetics_locale.validator.meta
            - %lunetics_locale.switcher.use_referrer%
            - %lunetics_locale.switcher.redirect_to_route%
            - %lunetics_locale.switcher.redirect_statuscode%
            - @service_container

    study_logic:
        class: Cyclogram\FrontendBundle\Service\StudyLogic
        arguments: [@service_container]
        
    study_controller_listener:
        class: Cyclogram\StudyBundle\Listener\ControllerListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController } 

#aop
    check_pointcut:
        class: Cyclogram\FrontendBundle\Aop\CheckPointcut
        arguments:
            - @annotation_reader
        tags:
            - { name: jms_aop.pointcut, interceptor: check_interceptor }    
                    
    check_interceptor:
        class: Cyclogram\FrontendBundle\Aop\CheckInterceptor
        arguments: 
            - @annotation_reader

