services:
    cyclogram.common:
        class: Cyclogram\CyclogramCommon
        arguments: ['@service_container']
        
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension
            
    twig.globals_extension:
        class: Cyclogram\FrontendBundle\Twig\GlobalExtension
        tags:
            - name: twig.extension
        arguments:
            - @service_container

    lunetics_locale.switcher_controller:
        class: Cyclogram\FrontendBundle\Controller\LocaleController
        arguments:
            - @router
            - @lunetics_locale.validator.meta
            - %lunetics_locale.switcher.use_referrer%
            - %lunetics_locale.switcher.redirect_to_route%
            - %lunetics_locale.switcher.redirect_statuscode%

    study_logic:
        class: Cyclogram\FrontendBundle\Service\StudyLogic
        arguments: [@service_container]
