<?php
/*
* This is part of the ProofPilot package.
*
* (c)2012-2013 Cyclogram, Inc, West Hollywood, CA <crew@proofpilot.com>
* ALL RIGHTS RESERVED
*
* This software is provided by the copyright holders to Manila Consulting for use on the
* Center for Disease Control's Evaluation of Rapid HIV Self-Testing among MSM in High
* Prevalence Cities until 2016 or the project is completed.
*
* Any unauthorized use, modification or resale is not permitted without expressed permission
* from the copyright holders.
*
* KnowatHome branding, URL, study logic, survey instruments, and resulting data are not part
* of this copyright and remain the property of the prime contractor.
*
*/

namespace Cyclogram\FrontendBundle\Controller;

use Cyclogram\Bundle\ProofPilotBundle\Entity\ParticipantStudyReminderLink;

use Symfony\Component\HttpFoundation\Response;

use Cyclogram\FrontendBundle\Form\MailingAddressForm;
use Cyclogram\FrontendBundle\Form\AboutMeForm;
use Symfony\Component\Validator\Constraints\Collection;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Cyclogram\FrontendBundle\Form\GeneralSettingForm;
use Cyclogram\CyclogramCommon;
use Cyclogram\Bundle\ProofPilotBundle\Entity\Participant;
use JMS\SecurityExtraBundle\Annotation\Secure;

/**
 * @Route("/main")
 */
class GeneralSettingsController  extends Controller
{

    /**
     * @Route("/general_settings", name="_settings")
     * @Secure(roles="ROLE_PARTICIPANT, IS_AUTHENTICATED_REMEMBERED")
     * @Template()
     */
    public function generalSettingsAction()
    {
        $participant = $this->get('security.context')->getToken()->getUser();
        $request = $this->getRequest();
        $em = $this->getDoctrine()->getManager();
        $surveyscount = $em->getRepository('CyclogramProofPilotBundle:ParticipantInterventionLink')->getActiveParticipantInterventionsCount($participant);
        $locale =$participant->getLocale() ? $participant->getLocale() : $request->getLocale();
        $parameters["lastaccess"] = new \DateTime();
        $parameters["expandedFormClass"] = '';
        $parameters["passwordConfirmShow"] = false;
        $parameters["phoneConfirmShow"] = false;
         
        if($participant->getFacebookId())
            $parameters["user"]["avatar"] = "http://graph.facebook.com/" . $participant->getParticipantUsername() . "/picture?width=80&height=82";

        $form = $this->createForm(new GeneralSettingForm($this->container));

        $clientIp = $request->getClientIp();
        if ($clientIp == '127.0.0.1') {
            $form->get('newPhoneNumberSmall')->setData(380);
        }
        $geoip = $this->get('maxmind.geoip')->lookup($clientIp);
        if ($geoip != false) {
            $countryCode = $geoip->getCountryCode();
            $country = $em->getRepository('CyclogramProofPilotBundle:Country')->findOneByCountryCode($countryCode);
            if (isset($country)){
                $form->get('newPhoneNumberSmall')->setData($country->getDailingCode());
            }
        }
        
        if ($request->getMethod() == 'POST') {
            $form->handleRequest($request);

            if ($form->isValid()) {
                $data = $form->getData();

                if($form->get('userNameConfirm')->isClicked()) {
                    $participant->setParticipantUsername($data['newUserName']);
                    $em->persist($participant);
                    $em->flush();
                    $parameters['message'] = $this->get('translator')->trans("username_change", array(), "general_settings", $locale);
                } elseif ($form->get('passwordSendSMS')->isClicked()) {
                    $participantSMSCode = CyclogramCommon::getAutoGeneratedCode(4);
                    $participant->setParticipantMobileSmsCode($participantSMSCode);
                    $sms = $this->get('sms');
                    $message = $this->container->get('translator')->trans('sms_password_text', array(), "general_settings",  $locale);
                    $sentSms = $sms->sendSmsAction( array('message' => $message.' '.$participantSMSCode, 'phoneNumber'=>$participant->getParticipantMobileNumber()) );
                    if($sentSms) {
                        $session = $request->getSession();
                        $session->set('newPassword', $data['newPassword']);
                        $em->persist($participant);
                        $em->flush($participant);
                        $parameters['message'] = $this->get('translator')->trans("confirm_sms_send", array(), "general_settings", $locale);
                    }
                    $parameters["passwordConfirmShow"] = true;
                    $parameters["expandedFormClass"] = 'password';
                } elseif ($form->get('passwordConfirm')->isClicked()) {
                    $session = $request->getSession();
                    if ($session->has('newPassword')) {
                        $factory = $this->get('security.encoder_factory');
                        $encoder = $factory->getEncoder($participant);
                        
                        $participant->setParticipantPassword($encoder->encodePassword($session->get('newPassword'), $participant->getSalt()));
                        $em->persist($participant);
                        $em->flush($participant);
                        $session->invalidate();
                        $parameters['message'] = $this->get('translator')->trans("password_change", array(), "general_settings", $locale);
                    }
                } elseif ($form->get('emailConfirm')->isClicked()) {
                    $participant->setParticipantEmail($data['newEmail']);
                    $participant->setParticipantEmailConfirmed(false);
                    $em->persist($participant);
                    $em->flush($participant);

                    $cc = $this->get('cyclogram.common');

                    $embedded = array();
                    $embedded = $cc->getEmbeddedImages();
                    
                    $parameters['email'] = $participant->getParticipantEmail();
                    $parameters['locale'] = $locale;
                    $parameters['host'] = $this->container->getParameter('site_url');
                    $parameters['code'] = $participant->getParticipantEmailCode();
                    $parameters["studies"] = $this->getDoctrine()->getRepository('CyclogramProofPilotBundle:Study')->getRandomStudyInfo($locale, $participant);
                    
                    $cc->sendMail(null,
                            $participant->getParticipantEmail(),
                            $this->get('translator')->trans("email_title_verify", array(), "email", $locale),
                            'CyclogramFrontendBundle:Email:email_confirmation.html.twig',
                            null,
                            $embedded,
                            true,
                            $parameters);
                    $parameters['message'] = $this->get('translator')->trans("email_change", array(), "general_settings", $locale);
                } elseif ($form->get('phoneSendSMS')->isClicked()) {
                    $participantSMSCode = CyclogramCommon::getAutoGeneratedCode(4);
                    $participant->setParticipantMobileSmsCode($participantSMSCode);
                    
                    $sms = $this->get('sms');
                             $message = $this->container->get('translator')->trans('sms_phone_text', array(), "general_settings",  $locale);
                    $sentSms = $sms->sendSmsAction( array('message' => $message.' '.$participantSMSCode, 'phoneNumber'=>$participant->getParticipantMobileNumber()) );
                    if($sentSms) {
                        $session = $request->getSession();
                        $session->set('newPhoneNumber', array($data['newPhoneNumberSmall'],$data['newPhoneNumberWide']));
                        $em->persist($participant);
                        $em->flush($participant);
                        $parameters['message'] = $this->get('translator')->trans("confirm_sms_send", array(), "general_settings", $locale);
                    }
                    $parameters["phoneConfirmShow"] = true;
                    $parameters["expandedFormClass"] = 'mobile';
                } elseif ($form->get('phoneConfirm')->isClicked()) {
                    $session = $request->getSession();
                    if ($session->has('newPhoneNumber')) {
                        $newPhoneNumber = $session->get('newPhoneNumber');
                        $participant->setParticipantMobileNumber($newPhoneNumber[0].$newPhoneNumber[1]);
                        $em->persist($participant);
                        $em->flush($participant);
                        $session->invalidate();
                        $parameters['message'] = $this->get('translator')->trans("mobile_number_change", array(), "general_settings", $locale);
                    }
                } elseif($form->get('incentiveEmailConfirm')->isClicked()) {
                        $participant->setParticipantAppreciationEmail($data['newIncentiveEmail']);
                        $em->persist($participant);
                        $em->flush($participant);
                        $parameters['message'] = $this->get('translator')->trans("appreciation_email_change", array(), "general_settings", $locale);
                } elseif($form->get('languageConfirm')->isClicked()) {
                    $language = $em->getRepository('CyclogramProofPilotBundle:Language')->findOneByLocale($data['languageSelect']);
                    $participant->setParticipantLanguage($language);
                    $participant->setLocale($data['languageSelect']);
                    $em->persist($participant);
                    $em->flush();
                    return $this->redirect($this->generateUrl("_settings", array('_locale' => $data['languageSelect'])));
                }
            } 
            else {
               if($form->get('userNameConfirm')->isClicked()) {
                   $parameters["expandedFormClass"] = 'username';
                } elseif ($form->get('passwordSendSMS')->isClicked()) {
                    $parameters["expandedFormClass"] = 'password';
                } elseif ($form->get('passwordConfirm')->isClicked()) {
                    $parameters["expandedFormClass"] = 'password';
                } elseif ($form->get('emailConfirm')->isClicked()) {
                    $parameters["expandedFormClass"] = 'email';
                } elseif ($form->get('phoneSendSMS')->isClicked()) {
                    $parameters["expandedFormClass"] = 'mobile';
                } elseif ($form->get('phoneConfirm')->isClicked()) {
                    $parameters["expandedFormClass"] = 'mobile';
                } elseif ($form->get('incentiveEmailConfirm')->isClicked()) {
                    $parameters["expandedFormClass"] = 'incentiveEmail';
                } 
            }
        }
        
        $parameters["participant"] = $participant;
        
        $parameters["user"]["name"] = $participant->getParticipantFirstname() . ' ' . $participant->getParticipantLastname();
        $parameters["user"]["username"] = $participant->getParticipantUsername();
        $parameters["user"]["last_access"] = $participant->getParticipantLastTouchDatetime();
        
        $parameters['form'] = $form->createView();
            
        return $this->render('CyclogramFrontendBundle:GeneralSettings:general_settings.html.twig', $parameters);
    }
    
    /**
     * @Route("/shipping_information/{update}", name="_shipping", defaults={"update"=null})
     * @Secure(roles="ROLE_PARTICIPANT, IS_AUTHENTICATED_REMEMBERED")
     * @Template()
     */
    public function generalShippingAction($update)
    {
        $participant = $this->get('security.context')->getToken()->getUser();
        $request = $this->getRequest();
        $em = $this->getDoctrine()->getManager();
        $surveyscount = $em->getRepository('CyclogramProofPilotBundle:ParticipantInterventionLink')->getActiveParticipantInterventionsCount($participant);
        $parameters["lastaccess"] = new \DateTime();
        if ($update)
            $parameters["update_data"] = $update;
        $parameters["expandedFormClass"] = '';
        $parameters["participant"] = $participant;
        
        $parameters["user"]["name"] = $participant->getParticipantFirstname() . ' ' . $participant->getParticipantLastname();
        $parameters["user"]["username"] = $participant->getParticipantUsername();
        $parameters["user"]["last_access"] = $participant->getParticipantLastTouchDatetime();
        if($participant->getFacebookId())
            $parameters["user"]["avatar"] = "http://graph.facebook.com/" . $participant->getParticipantUsername() . "/picture?width=80&height=82";
    
        $collectionConstraint = new Collection(array(
                'participantFirstname'     =>  new NotBlank(),
                'participantLastname'        => new NotBlank(),
                'participantAddress1'      => new NotBlank(),
                'participantZipcode' => new NotBlank(),
                'city'     => new NotBlank(),
                'state'    => new NotBlank()
        ));
        $form = $this->createForm(new MailingAddressForm($this->container), array('constraints' => $collectionConstraint));
    
        if ($participant->getParticipantFirstname()){
            $form->get('participantFirstname')->setData($participant->getParticipantFirstname());
        }
        if ($participant->getParticipantLastname()){
            $form->get('participantLastname')->setData($participant->getParticipantLastname());
        }
        if ($participant->getParticipantAddress1()){
            $form->get('participantAddress1')->setData($participant->getParticipantAddress1());
        }
        if ($participant->getParticipantAddress2()){
            $form->get('participantAddress2')->setData($participant->getParticipantAddress2());
        }
        if ($participant->getParticipantZipcode()){
            $form->get('participantZipcode')->setData($participant->getParticipantZipcode());
        }
        if ($participant->getCity()){
            $city = $participant->getCity();
            $form->get('city')->setData($city->getCityName());
            $form->get('cityId')->setData($city->getCityId());
        }
        if ($participant->getState()){
            $state = $participant->getState();
            $form->get('state')->setData($state->getStateCode());
            $form->get('stateId')->setData($state->getstateId());
        }
        $sign = $participant->getParticipantDeliverySign();
        if (isset($sign)){
            if ($sign == true) {
                $form['sign']->setData('sign');
            }else{
                $form['sign']->setData('notSign');
            }
        }
    
        if ($request->getMethod() == 'POST') {
            $form->handleRequest($request);
    
            if ($form->isValid()) {
                $this->get('study_logic')->participantDefaultInterventionLogic($participant, 'shippingInformation');
                $form = $form->getData();
                $participant->setParticipantFirstname($form['participantFirstname']);
                $participant->setParticipantLastname($form['participantLastname']);
                $participant->setParticipantAddress1($form['participantAddress1']);
                $participant->setParticipantAddress2($form['participantAddress2']);
                $participant->setParticipantZipcode($form['participantZipcode']);
                if (!empty($form['cityId'])) {
                    $city = $em->getRepository('CyclogramProofPilotBundle:City')->find($form['cityId']);
                    $participant->setCity($city);
                } else {
                    $participant->setCityName($form['city']);
                }
                if (!empty($form['stateId'])) {
                    $state = $em->getRepository('CyclogramProofPilotBundle:State')->find($form['stateId']);
                    $participant->setState($state);
                } else {
                    $participant->setParticipantState($form['state']);
                }
                $country = $em->getRepository('CyclogramProofPilotBundle:Country')->find(1);
                $participant->setCountry($country);
                if ($form['sign'] == 'notSign')
                    $participant->setParticipantDeliverySign(false);
                else
                    $participant->setParticipantDeliverySign(true);
    
                $em->persist($participant);
                $em->persist($participant);
                $em->flush($participant);
                 return $this->redirect($this->generateUrl("_shipping",
                                array('update' => true)));
 
            }
        }
        
        $parameters['formShippingInformation'] = $form->createView();
    
        return $this->render('CyclogramFrontendBundle:GeneralSettings:shipping_information.html.twig', $parameters);
    }
    
    /**
     * @Route("/about_me", name="_about_me")
     * @Secure(roles="ROLE_PARTICIPANT, IS_AUTHENTICATED_REMEMBERED")
     * @Template()
     */
    public function aboutMeAction() {
        $participant = $this->get('security.context')->getToken()->getUser();
        $request = $this->getRequest();
        $em = $this->getDoctrine()->getManager();
        $locale =$participant->getLocale() ? $participant->getLocale() : $request->getLocale();
        $parameters["lastaccess"] = new \DateTime();
        $parameters["expandedFormClass"] = '';
         
        if($participant->getFacebookId())
            $parameters["user"]["avatar"] = "http://graph.facebook.com/" . $participant->getParticipantUsername() . "/picture?width=80&height=82";
        
        $form = $this->createForm(new AboutMeForm($this->container));
        
        if ($request->getMethod() == 'POST') {
            $form->handleRequest($request);
        
            if ($form->isValid()) {
                $data = $form->getData();
                $form->get('countryConfirm');
                if($form->get('countryConfirm')->isClicked() || ($data['validationCheck'] == 'country')) {
                    $participant->setCountry($data['countrySelect']);
                    $em->persist($participant);
                    $em->flush();
                    if ($request->isXmlHttpRequest())
                        return new Response(json_encode(array('error' => false, 'message' => $this->get('translator')->trans("country_change", array(), "about_me", $locale), 'data' => $data['countrySelect']->getCountryName(), 'name' => 'country')));
                    else
                        $parameters['message'] = $this->get('translator')->trans("country_change", array(), "about_me", $locale);
                } elseif ($form->get('zipcodeConfirm')->isClicked() || ($data['validationCheck'] == 'zipcode')) {
                    $participant->setParticipantZipCode($data['newzipcode']);
                    $em->persist($participant);
                    $em->flush();
                    if ($request->isXmlHttpRequest())
                        return new Response(json_encode(array('error' => false, 'message' => $this->get('translator')->trans("zipcode_change", array(), "about_me", $locale), 'data' => $data['newzipcode'], 'name' => 'zipcode')));
                    else
                        $parameters['message'] = $this->get('translator')->trans("zipcode_change", array(), "about_me", $locale);
                } elseif ($form->get('birthdateConfirm')->isClicked() || ($data['validationCheck'] == 'birthdate')) {
                    $datePices = explode("/", $data['birthdateSelect']);
                    $date = new \DateTime($datePices[2].'-'.$datePices[0].'-'.$datePices[1]);
                    $participant->setParticipantBirthdate($date );
                    $em->persist($participant);
                    $em->flush();
                    if ($request->isXmlHttpRequest())
                        return new Response(json_encode(array('error' => false, 'message' => $this->get('translator')->trans("birthdate_change", array(), "about_me", $locale), 'data' => $data['birthdateSelect'], 'name' => 'birthdate')));
                    else
                        $parameters['message'] = $this->get('translator')->trans("birthdate_change", array(), "about_me", $locale);
                } elseif ($form->get('sexConfirm')->isClicked() || ($data['validationCheck'] == 'sex')) {
                    $sex =  $em->getRepository('CyclogramProofPilotBundle:Sex')->findOneBySexName($data['sexSelect']);
                    $participant->setSex($sex);
                    $em->persist($participant);
                    $em->flush();
                    if ($request->isXmlHttpRequest())
                        return new Response(json_encode(array('error' => false, 'message' => $this->get('translator')->trans("sex_change", array(), "about_me", $locale), 'data' => $sex->getSexName(), 'name' => 'sex')));
                    else
                        $parameters['message'] = $this->get('translator')->trans("sex_change", array(), "about_me", $locale);
                } elseif ($form->get('interestedConfirm')->isClicked() || ($data['validationCheck'] == 'interested')) {
                    $interested= "";
                    foreach ($data['interestedSelect'] as $interest){
                        $interested.= $interest;
                    }
                    $participant->setParticipantInterested($interested);
                    $em->persist($participant);
                    $em->flush();
                    if (isset($interested) && $interested == 'w') {
                        $interest = 'Woman';
                    } elseif (isset($interested) && $interested == 'm') {
                        $interest= 'Man';
                    } elseif (isset($interested) && $interested == 'mw') {
                        $interest = 'Man&Woman';
                    }else {
                        $interest = "";
                    }
                    if ($request->isXmlHttpRequest())
                        return new Response(json_encode(array('error' => false, 'message' => $this->get('translator')->trans("interest_change", array(), "about_me", $locale), 'data' => $interest, 'name' => 'interested')));
                    else
                        $parameters['message'] = $this->get('translator')->trans("interest_change", array(), "about_me", $locale);
                } elseif ($form->get('raceConfirm')->isClicked() || ($data['validationCheck'] == 'race')) {
                    $race = $em->getRepository('CyclogramProofPilotBundle:Race')->findOneByRaceName($data['raceSelect']);
                    $participant->setRace($race);
                    $em->persist($participant);
                    $em->flush();
                    if ($request->isXmlHttpRequest())
                        return new Response(json_encode(array('error' => false, 'message' => $this->get('translator')->trans("race_change", array(), "about_me", $locale), 'data' => $data['raceSelect'], 'name' => 'race')));
                    else
                        $parameters['message'] = $this->get('translator')->trans("race_change", array(), "about_me", $locale);
                } 
            }
            else {
                if ($request->isXmlHttpRequest()) {
                    $messages = array();
                    $validator = $this->container->get('validator');
                    $errors = $validator->validate($form);
                    foreach ($errors as $err) {
                        if(strpos($err->getPropertyPath(),'[')) {
                            $property = substr($err->getPropertyPath(),strpos($err->getPropertyPath(),'[')+1,strlen($err->getPropertyPath()));
                            $len = strpos($property,']');
                            $property = substr($property,0,$len);
                        }
                        $messages[]= array('property' => $property ,
                                'message' => $err->getMessage());
                    }
                    return new Response(json_encode(array('error' => true,'messages' => $messages)));
                }
                if($form->get('countryConfirm')->isClicked()) {
                    $parameters["expandedFormClass"] = 'country';
                } elseif ($form->get('zipcodeConfirm')->isClicked()) {
                    $parameters["expandedFormClass"] = 'zipCode';
                } elseif ($form->get('birthdateConfirm')->isClicked()) {
                    $parameters["expandedFormClass"] = 'birthdate';
                } elseif ($form->get('sexConfirm')->isClicked()) {
                    $parameters["expandedFormClass"] = 'sex';
                } elseif ($form->get('interestedConfirm')->isClicked()) {
                    $parameters["expandedFormClass"] = 'interested';
                } elseif ($form->get('raceConfirm')->isClicked()) {
                    $parameters["expandedFormClass"] = 'race';
                } 
            }
        }
        $interested = $participant->getParticipantInterested();
        if (isset($interested) && $interested == 'w') {
            $parameters['interest'] = 'Woman';
        } elseif (isset($interested) && $interested == 'm') {
            $parameters['interest'] = 'Man';
        } elseif (isset($interested) && $interested == 'mw') {
            $parameters['interest'] = 'Man&Woman';
        }else {
            $parameters['interest'] = "";
        }
        $parameters['participant'] = $participant;
        $parameters["user"]["name"] = $participant->getParticipantFirstname() . ' ' . $participant->getParticipantLastname();
        $parameters["user"]["username"] = $participant->getParticipantUsername();
        $parameters["user"]["last_access"] = $participant->getParticipantLastTouchDatetime();
        $parameters['formAboutMe'] = $form->createView();
        
        return $this->render('CyclogramFrontendBundle:GeneralSettings:about_me.html.twig', $parameters);
    }

}
