<?php

namespace Cyclogram\Bundle\ProofPilotBundle\Repository\LimeSurvey;

use Doctrine\ORM\EntityRepository;

/**
 * StudyLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LimeSurveysLanguagesettingsRepository extends EntityRepository
{
    public function getSurveyLocale ($surveyId, $locale)
    {
        $fallbacks = array(
                'en'=> array('en'),
                'es'=> array('es', 'en'),
                'pt'=> array('pt', 'en'),
                'fr'=> array('fr', 'en'),
                'pt_BR'=> array('pt-BR', 'pt', 'en'),
                'es_MX'=> array('es-MX', 'es', 'en')
        );
    
    
        //try to get using full locale
        $results = $this->getEntityManager()
                ->createQuery("
                SELECT lslr
                FROM CyclogramProofPilotBundleLime:LimeSurveysLanguagesettings lslr
                WHERE
                lslr.surveylsLanguage IN (:locales)
                AND
                lslr.surveylsSurveyId = :surveyid
                ")
                ->setParameter('locales', $fallbacks[$locale])
                ->setParameter('surveyid', $surveyId)
                ->getResult();
    
        foreach($fallbacks[$locale] as $locale) {
            foreach($results as $result) {
                if($result->getSurveylsLanguage() == $locale)
                    return $result->getSurveylsLanguage();
            }
        }
    
    }
}
