<?php
/*
* This is part of the ProofPilot package.
*
* (c)2012-2013 Cyclogram, Inc, West Hollywood, CA <crew@proofpilot.com>
* ALL RIGHTS RESERVED
*
* This software is provided by the copyright holders to Manila Consulting for use on the
* Center for Disease Control's Evaluation of Rapid HIV Self-Testing among MSM in High
* Prevalence Cities until 2016 or the project is completed.
*
* Any unauthorized use, modification or resale is not permitted without expressed permission
* from the copyright holders.
*
* KnowatHome branding, URL, study logic, survey instruments, and resulting data are not part
* of this copyright and remain the property of the prime contractor.
*
*/

namespace Cyclogram\Bundle\ProofPilotBundle\Repository\LimeSurvey;

use Doctrine\ORM\EntityRepository;

/**
 * StudyLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LimeSurveysLanguagesettingsRepository extends EntityRepository
{
    public function getSurvey($surveyId, $locale)
    {
        $fallbacks = array(
                'en'=> array('en'),
                'es'=> array('es', 'es-MX', 'en'),
                'pt'=> array('pt', 'pt-BR', 'en'),
                'fr'=> array('fr', 'en'),
        		'zh_cn'=> array('zh_cn', 'en'),
                'pt_BR'=> array('pt-BR', 'pt', 'en'),
                'es_MX'=> array('es-MX', 'es', 'en')
        );
    
    
        //try to get using full locale
        $results = $this->getEntityManager()
                ->createQuery("
                SELECT lslr
                FROM CyclogramProofPilotBundleLime:LimeSurveysLanguagesettings lslr
                WHERE
                lslr.surveylsLanguage IN (:locales)
                AND
                lslr.surveylsSurveyId = :surveyid
                ")
                ->setParameter('locales', $fallbacks[$locale])
                ->setParameter('surveyid', $surveyId)
                ->getResult();
    
        foreach($fallbacks[$locale] as $locale) {
            foreach($results as $result) {
                if($result->getSurveylsLanguage() == $locale)
                    return $result;
            }
        }
    
    }
}
