<?php
/*
* This is part of the ProofPilot package.
*
* (c)2012-2013 Cyclogram, Inc, West Hollywood, CA <crew@proofpilot.com>
* ALL RIGHTS RESERVED
*
* This software is provided by the copyright holders to Manila Consulting for use on the
* Center for Disease Control's Evaluation of Rapid HIV Self-Testing among MSM in High
* Prevalence Cities until 2016 or the project is completed.
*
* Any unauthorized use, modification or resale is not permitted without expressed permission
* from the copyright holders.
*
* KnowatHome branding, URL, study logic, survey instruments, and resulting data are not part
* of this copyright and remain the property of the prime contractor.
*
*/
namespace Cyclogram\Bundle\ProofPilotBundle\Repository;

use Cyclogram\Bundle\ProofPilotBundle\Entity\ParticipantContactTimeLink;
use Cyclogram\Bundle\ProofPilotBundle\Entity\ParticipantContactTime;

use Doctrine\ORM\EntityRepository;

/**
 * StudyLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantContactTimeRepository extends EntityRepository
{
    /**
     * Get current contact time period
     * @param unknown_type $participant
     */
    public function getCurrentContactPeriod (\DateTime $current=null)
    {
        $contactTimes = $this->findAll();
        
        if(!$current)
            $current = new \DateTime();
        

        foreach($contactTimes as $ct) {
            $start = $ct->getParticipantContactTimesRangeStart();
            $end = $ct->getParticipantContactTimesRangeEnd();

            $curtime = (int)$current->format("Gis");
            $starttime = (int)$start->format("Gis");
            $endtime = (int)$end->format("Gis"); 
            
            if($curtime >= $starttime && $curtime <= $endtime)
                return $ct;
        }
    }



}
