<?php
/*
* This is part of the ProofPilot package.
*
* (c)2012-2013 Cyclogram, Inc, West Hollywood, CA <crew@proofpilot.com>
* ALL RIGHTS RESERVED
*
* This software is provided by the copyright holders to Manila Consulting for use on the
* Center for Disease Control's Evaluation of Rapid HIV Self-Testing among MSM in High
* Prevalence Cities until 2016 or the project is completed.
*
* Any unauthorized use, modification or resale is not permitted without expressed permission
* from the copyright holders.
*
* KnowatHome branding, URL, study logic, survey instruments, and resulting data are not part
* of this copyright and remain the property of the prime contractor.
*
*/
namespace Cyclogram\Bundle\ProofPilotBundle\Repository;

use Cyclogram\Bundle\ProofPilotBundle\Entity\ParticipantStudyReminderLink;

use Doctrine\ORM\EntityRepository;

/**
 * StudyLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantStudyReminderLinkRepository extends EntityRepository
{
    
    /**
     * Get the participant study reminder link, if not found creates one
     * @param unknown_type $participant
     * @param unknown_type $reminder
     * @return Ambigous <\Cyclogram\Bundle\ProofPilotBundle\Entity\ParticipantStudyReminderLink, \Doctrine\ORM\mixed, NULL, mixed, unknown>
     */
    public function getParticipantReminderLink ($participant, $reminder)
    {
        $query = $this->getEntityManager()
        ->createQuery("
                SELECT prl
                FROM CyclogramProofPilotBundle:ParticipantStudyReminderLink prl
                WHERE
                prl.participant = :participant
                AND 
                prl.participantStudyReminder = :reminder
                ")
                ->setParameter("participant", $participant)
                ->setParameter("reminder",$reminder);
        
        $result = $query->getOneOrNullResult();
        
        if(!$result)
            $result = new ParticipantStudyReminderLink();
        
        return $result;

    }
}
