<?php
namespace Cyclogram\Bundle\ProofPilotBundle\Repository;

use Cyclogram\Bundle\ProofPilotBundle\Entity\ParticipantContactTimeLink;
use Cyclogram\Bundle\ProofPilotBundle\Entity\ParticipantContactTime;

use Doctrine\ORM\EntityRepository;

/**
 * StudyLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantContactTimeRepository extends EntityRepository
{
    /**
     * Get current contact time period
     * @param unknown_type $participant
     */
    public function getCurrentContactPeriod (\DateTime $current=null)
    {
        $contactTimes = $this->findAll();
        
        if(!$current)
            $current = new \DateTime();
        

        foreach($contactTimes as $ct) {
            $start = $ct->getParticipantContactTimesRangeStart();
            $end = $ct->getParticipantContactTimesRangeEnd();

            $curtime = (int)$current->format("Gis");
            $starttime = (int)$start->format("Gis");
            $endtime = (int)$end->format("Gis"); 
            
            if($curtime >= $starttime && $curtime <= $endtime)
                return $ct;
        }
    }



}
