<?php
namespace Cyclogram\Bundle\ProofPilotBundle\Repository;

use Cyclogram\Bundle\ProofPilotBundle\Entity\ParticipantContactTimeLink;

use Doctrine\ORM\EntityRepository;

/**
 * StudyLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantContactTimeLinkRepository extends EntityRepository
{
    /**
     * Get the participant contact time link
     * @param unknown_type $participant
     * @param unknown_type $reminder
     * @return Ambigous <\Cyclogram\Bundle\ProofPilotBundle\Entity\ParticipantStudyReminderLink, \Doctrine\ORM\mixed, NULL, mixed, unknown>
     */
    public function getParticipantContactTimeLink ($participant, $contactTime)
    {
        $query = $this->getEntityManager()
        ->createQuery("
                SELECT pctl
                FROM CyclogramProofPilotBundle:ParticipantContactTimeLink pctl
                WHERE
                pctl.participant = :participant
                AND
                pctl.participantContactTime = :contacttime
                ")
                ->setParameter("participant", $participant)
                ->setParameter("contacttime", $contactTime);
    
        $result = $query->getOneOrNullResult();
        
        return $result;
    }

    
    
    
    public function updateParticipantContactTimeLink($participant, $contactTime, $active, $timezone)
    {
        $em = $this->getEntityManager();
        if(!$active) {
            $em->createQuery("
                    DELETE FROM CyclogramProofPilotBundle:ParticipantContactTimeLink pctl
                    WHERE
                    pctl.participant = :participant
                    AND
                    pctl.participantContactTime = :contacttime
                    ")
                    ->setParameter("participant", $participant)
                    ->setParameter("contacttime", $contactTime)
                    ->execute();
        } else {
            $contactTimeLinks = $em->createQuery("
                SELECT COUNT(pctl)
                FROM CyclogramProofPilotBundle:ParticipantContactTimeLink pctl
                WHERE
                pctl.participant = :participant
                AND
                pctl.participantContactTime = :contacttime
            ")
            ->setParameter("participant", $participant)
            ->setParameter("contacttime", $contactTime)
            ->getSingleScalarResult();
            
            if(!$contactTimeLinks) {
                $contactTimeLink = new ParticipantContactTimeLink();
                $contactTimeLink->setParticipant($participant);
                $contactTimeLink->setParticipantContactTime($contactTime);
                $contactTimeLink->setParticipantTimezone($timezone);
                $contactTimeLink->setParticipantContactTimeStart(new \DateTime());
                $contactTimeLink->setParticipantContactTimeEnd(new \DateTime());
                $em->persist($contactTimeLink);
                $em->flush();
            } else {
                $a = $em->createQuery("
                        UPDATE CyclogramProofPilotBundle:ParticipantContactTimeLink pctl
                        SET pctl.participantTimezone = " . $timezone->getParticipantTimezoneId() . " 
                        WHERE
                        pctl.participant = :participant
                        AND
                        pctl.participantContactTime = :contacttime
                        ")
                        ->setParameter("participant", $participant)
                        ->setParameter("contacttime", $contactTime)
                        ->execute();
            }
        }
    }
    

}
