parameters:
    kernel.listener.login.class: Cyclogram\FrontendBundle\Listener\SecurityListener

services:
    kernel.listener.login:
        class: %kernel.listener.login.class%
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
        arguments: [@router, @security.context, @service_container]